---
name: "build-push-docker-image"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Match only a full sematic version tag, i.e. v20.15.10

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        # This action requires minimum permissions of:
        # permissions:
        #   contents: write
        #   pull-requests: write
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

  build-and-push-image:
    name: Build and push Docker image
    needs: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for the AWS role assumption
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Github Container registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      #     aws-region: ${{ vars.AWS_ECR_REGION }}

      # - name: Login to Amazon ECR
      #   uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      #   with:
      #     ecr: true
      #     registry: ${{ secrets.AWS_ECR_ACCOUNT }}.dkr.ecr.${{ vars.AWS_ECR_REGION }}.amazonaws.com

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4.6.0
        with:
          images: |
            ghcr.io/${{ github.repository }}
          # images: |
          #   ghcr.io/${{ github.repository }}
          #   ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_IMAGE_NAME }}
          #   ${{ secrets.AWS_ECR_ACCOUNT }}.dkr.ecr.${{ vars.AWS_ECR_REGION }}.amazonaws.com/${{ vars.AWS_ECR_IMAGE_NAME}}

      - name: Build and push Docker image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
